In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_excel("/Users/basillatif/Desktop/NFL Forecast Model/2019 Season Data with Playoffs.xlsx")

In [3]:
data

Team1  Week  Game Number Game Location  \
0      Arizona Cardinals     1            1           NaN   
1      Arizona Cardinals     2            2          AWAY   
2      Arizona Cardinals     3            3           NaN   
3      Arizona Cardinals     4            4           NaN   
4      Arizona Cardinals     5            5          AWAY   
..                   ...   ...          ...           ...   
529  Washington Redskins    13           12          AWAY   
530  Washington Redskins    14           13          AWAY   
531  Washington Redskins    15           14           NaN   
532  Washington Redskins    16           15           NaN   
533  Washington Redskins    17           16          AWAY   

                   Team2  Team1_Score  Team2_Score  Team1_Passing  \
0          Detroit Lions         27.0         27.0          275.0   
1       Baltimore Ravens         17.0         23.0          329.0   
2      Carolina Panthers         20.0         38.0          127.0   
3       Seattle Seahawks         10.0         27.0          206.0   
4     Cincinnati Bengals         26.0         23.0          248.0   
..                   ...          ...          ...            ...   
529    Carolina Panthers         29.0         21.0          114.0   
530    Green Bay Packers         15.0         20.0          141.0   
531  Philadelphia Eagles         27.0         37.0          251.0   
532      New York Giants         35.0         41.0          281.0   
533       Dallas Cowboys         16.0         47.0          183.0   

     Team1_Rushing  Team1_Turnovers  Team2_Passing  Team2_Rushing  \
0            112.0                1          361.0          116.0   
1             20.0                0          258.0          182.0   
2            121.0                2          240.0          173.0   
3            115.0                1          225.0          115.0   
4            266.0                0          262.0          108.0   
..             ...              ...            ...            ...   
529          248.0                0          213.0           65.0   
530          121.0                1          167.0          174.0   
531          101.0                1          258.0          157.0   
532           80.0                0          346.0          206.0   
533           88.0                2          294.0          223.0   

     Team2_Turnovers  
0                  2  
1                  0  
2                  1  
3                  0  
4                  0  
..               ...  
529                2  
530                1  
531                1  
532                0  
533                1  

[534 rows x 13 columns]

#Who scored the most points this season
#data1 = data.groupby('Team1')['Team1_Score'].sum() 
#data1.sort_values(ascending=False)
#Who had the most passing yards this season 
data2 = data.groupby('Team1')['Team1_Passing'].sum()
data2.sort_values(ascending=False)
#Who had the most rushing yards
data3 = data.groupby('Team1')['Team1_Rushing'].sum()
data3.sort_values(ascending=False)

In [4]:
chiefs = data.loc[data['Team1'] == 'Kansas City Chiefs']
chiefs.drop(chiefs.tail(1).index,inplace=True)
chiefs.head()

/Users/basillatif/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Team1  Week  Game Number Game Location  \
246  Kansas City Chiefs     1            1          AWAY   
247  Kansas City Chiefs     2            2          AWAY   
248  Kansas City Chiefs     3            3           NaN   
249  Kansas City Chiefs     4            4          AWAY   
250  Kansas City Chiefs     5            5           NaN   

                    Team2  Team1_Score  Team2_Score  Team1_Passing  \
246  Jacksonville Jaguars         40.0         26.0          378.0   
247       Oakland Raiders         28.0         10.0          436.0   
248      Baltimore Ravens         33.0         28.0          363.0   
249         Detroit Lions         34.0         30.0          315.0   
250    Indianapolis Colts         13.0         19.0          288.0   

     Team1_Rushing  Team1_Turnovers  Team2_Passing  Team2_Rushing  \
246          113.0                0          347.0           81.0   
247           31.0                1          178.0          129.0   
248          140.0                0          249.0          203.0   
249          123.0                3          261.0          186.0   
250           36.0                1          151.0          180.0   

     Team2_Turnovers  
246                2  
247                2  
248                0  
249                2  
250                1

In [5]:
niners = data.loc[data['Team1'] == 'San Francisco 49ers']
niners.drop(niners.tail(1).index,inplace=True)
niners.tail()

Team1  Week  Game Number Game Location              Team2  \
459  San Francisco 49ers    15           14           NaN    Atlanta Falcons   
460  San Francisco 49ers    16           15           NaN   Los Angeles Rams   
461  San Francisco 49ers    17           16          AWAY   Seattle Seahawks   
462  San Francisco 49ers    19           17           NaN  Minnesota Vikings   
463  San Francisco 49ers    20           18           NaN  Green Bay Packers   

     Team1_Score  Team2_Score  Team1_Passing  Team1_Rushing  Team1_Turnovers  \
459         22.0         29.0          193.0          120.0                2   
460         34.0         31.0          215.0          119.0                2   
461         26.0         21.0          270.0          128.0                0   
462         27.0         10.0          122.0          186.0                2   
463         37.0         20.0           69.0          285.0                0   

     Team2_Passing  Team2_Rushing  Team2_Turnovers  
459          201.0           89.0                1  
460          323.0           72.0                1  
461          223.0          125.0                0  
462          126.0           21.0                2  
463          296.0           62.0                3

In [6]:
#chiefs average data
chiefs_score = chiefs['Team1_Score'].mean()
chiefs_pass = chiefs['Team1_Passing'].mean()
chiefs_run = chiefs['Team1_Rushing'].mean()
chiefs_turnover = chiefs['Team1_Turnovers'].mean()
chiefs_turnover

0.8888888888888888

In [7]:
#niners average data 
niners_score = chiefs['Team1_Score'].mean()
niners_pass = chiefs['Team1_Passing'].mean()
niners_run = chiefs['Team1_Rushing'].mean()
niners_turnover = chiefs['Team1_Turnovers'].mean()
niners_turnover

0.8888888888888888

In [8]:
chiefs_playoff_avgs = np.array([21, 304, 115, 0.5]).reshape(1, -1)
chiefs_season_avgs = np.array([21, 284, 99, 0.89 ]).reshape(1, -1)
niners_playoff_avgs = np.array([21, 95, 235, 1]).reshape(1, -1)
niners_season_avgs = np.array([21, 283, 99, 0.89]).reshape(1, -1)

In [9]:
niners_playoff_avgs

array([[ 21,  95, 235,   1]])

#Building a random forest 
https://stackabuse.com/random-forest-algorithm-with-python-and-scikit-learn/
https://medium.com/@sametgirgin/random-forest-regression-in-5-steps-with-python-ee4259eca0de

In [10]:
#Splitting into attributes and labels. For game no, pass, rushing, turnovers
A = chiefs.iloc[:, 2].values
B = chiefs.iloc[:, 7:10].values
# concatenate 2 numpy arrays: column-wise
C = np.column_stack((A,B))
C

array([[  1., 378., 113.,   0.],
       [  2., 436.,  31.,   1.],
       [  3., 363., 140.,   0.],
       [  4., 315., 123.,   3.],
       [  5., 288.,  36.,   1.],
       [  6., 256.,  53.,   2.],
       [  7., 191.,  80.,   0.],
       [  8., 249.,  88.,   1.],
       [  9., 230., 147.,   1.],
       [ 10., 433.,  97.,   1.],
       [ 11., 180., 130.,   1.],
       [ 12., 163.,  96.,   0.],
       [ 13., 271.,  75.,   2.],
       [ 14., 327.,  92.,   1.],
       [ 15., 244., 106.,   0.],
       [ 16., 174., 162.,   1.],
       [ 17., 316., 118.,   1.],
       [ 18., 292., 112.,   0.]])

In [11]:
#Team 1 Score is my Label 
d = chiefs.iloc[:, 5].values
d

array([40., 28., 33., 34., 13., 24., 30., 24., 26., 32., 24., 40., 23.,
       23., 26., 31., 51., 35.])

In [12]:
L = niners.iloc[:, 2].values
M = niners.iloc[:, 7:10].values
# concatenate 2 numpy arrays: column-wise
O = np.column_stack((A,B))
O

array([[  1., 378., 113.,   0.],
       [  2., 436.,  31.,   1.],
       [  3., 363., 140.,   0.],
       [  4., 315., 123.,   3.],
       [  5., 288.,  36.,   1.],
       [  6., 256.,  53.,   2.],
       [  7., 191.,  80.,   0.],
       [  8., 249.,  88.,   1.],
       [  9., 230., 147.,   1.],
       [ 10., 433.,  97.,   1.],
       [ 11., 180., 130.,   1.],
       [ 12., 163.,  96.,   0.],
       [ 13., 271.,  75.,   2.],
       [ 14., 327.,  92.,   1.],
       [ 15., 244., 106.,   0.],
       [ 16., 174., 162.,   1.],
       [ 17., 316., 118.,   1.],
       [ 18., 292., 112.,   0.]])

In [13]:
p = niners.iloc[:, 5].values
p

array([31., 41., 24., 31., 20.,  9., 51., 28., 24., 36., 37., 17., 48.,
       22., 34., 26., 27., 37.])

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics

In [15]:
C_train, C_test, d_train, d_test = train_test_split(C, d, test_size=0.1, random_state=0)
#C_train, 
C_test
#d_train, d_test

array([[  2., 436.,  31.,   1.],
       [  7., 191.,  80.,   0.]])

In [16]:
#Feature Scaling
sc = StandardScaler()
C_train = sc.fit_transform(C_train)
C_test = sc.transform(C_test)

In [17]:
#Using the playoff games as an input FOR CHIEFS
regressor = RandomForestRegressor(n_estimators=200, random_state=0)
regressor.fit(C, d)
#regressor.fit(C_train, d_train)
y_pred = regressor.predict(chiefs_playoff_avgs)
#y_pred = regressor.predict(chiefs_playoff_avgs)
print(y_pred)

[38.89]


In [ ]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

In [ ]:
O_train, O_test, p_train, p_test = train_test_split(O, p, test_size=0.1, random_state=0)
p_test

In [ ]:
sc = StandardScaler()
O_train = sc.fit_transform(O_train)
O_test = sc.transform(O_test)

In [ ]:
#Using the playoff games as an input FOR 49ERS
regressor = RandomForestRegressor(n_estimators=200, random_state=0)
regressor.fit(O, p)
y_pred = regressor.predict(niners_playoff_avgs)
print(y_pred)

In [ ]:
#Using regular season as input 
regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(C_train, d_train)
y_pred = regressor.predict(d_test)
print(y_pred)

In [ ]:
#another article

In [ ]:
model = RandomForestClassifier(n_estimators=10)