In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel("/Users/basillatif/Desktop/NFL Forecast Model/2019 Season Data with Playoffs.xlsx")

In [3]:
data

Team1  Week  Game Number Game Location  \
0      Arizona Cardinals     1            1           NaN   
1      Arizona Cardinals     2            2          AWAY   
2      Arizona Cardinals     3            3           NaN   
3      Arizona Cardinals     4            4           NaN   
4      Arizona Cardinals     5            5          AWAY   
..                   ...   ...          ...           ...   
529  Washington Redskins    13           12          AWAY   
530  Washington Redskins    14           13          AWAY   
531  Washington Redskins    15           14           NaN   
532  Washington Redskins    16           15           NaN   
533  Washington Redskins    17           16          AWAY   

                   Team2  Team1_Score  Team2_Score  Team1_Passing  \
0          Detroit Lions         27.0         27.0          275.0   
1       Baltimore Ravens         17.0         23.0          329.0   
2      Carolina Panthers         20.0         38.0          127.0   
3       Seattle Seahawks         10.0         27.0          206.0   
4     Cincinnati Bengals         26.0         23.0          248.0   
..                   ...          ...          ...            ...   
529    Carolina Panthers         29.0         21.0          114.0   
530    Green Bay Packers         15.0         20.0          141.0   
531  Philadelphia Eagles         27.0         37.0          251.0   
532      New York Giants         35.0         41.0          281.0   
533       Dallas Cowboys         16.0         47.0          183.0   

     Team1_Rushing  Team1_Turnovers  Team2_Passing  Team2_Rushing  \
0            112.0                1          361.0          116.0   
1             20.0                0          258.0          182.0   
2            121.0                2          240.0          173.0   
3            115.0                1          225.0          115.0   
4            266.0                0          262.0          108.0   
..             ...              ...            ...            ...   
529          248.0                0          213.0           65.0   
530          121.0                1          167.0          174.0   
531          101.0                1          258.0          157.0   
532           80.0                0          346.0          206.0   
533           88.0                2          294.0          223.0   

     Team2_Turnovers  
0                  2  
1                  0  
2                  1  
3                  0  
4                  0  
..               ...  
529                2  
530                1  
531                1  
532                0  
533                1  

[534 rows x 13 columns]

#Who scored the most points this season
#data1 = data.groupby('Team1')['Team1_Score'].sum() 
#data1.sort_values(ascending=False)
#Who had the most passing yards this season 
data2 = data.groupby('Team1')['Team1_Passing'].sum()
data2.sort_values(ascending=False)
#Who had the most rushing yards
data3 = data.groupby('Team1')['Team1_Rushing'].sum()
data3.sort_values(ascending=False)

In [22]:
chiefs = data.loc[data['Team1'] == 'Kansas City Chiefs']
chiefs.drop(chiefs.tail(1).index,inplace=True)
chiefs

/Users/basillatif/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Team1  Week  Game Number Game Location  \
246  Kansas City Chiefs     1            1          AWAY   
247  Kansas City Chiefs     2            2          AWAY   
248  Kansas City Chiefs     3            3           NaN   
249  Kansas City Chiefs     4            4          AWAY   
250  Kansas City Chiefs     5            5           NaN   
251  Kansas City Chiefs     6            6           NaN   
252  Kansas City Chiefs     7            7          AWAY   
253  Kansas City Chiefs     8            8           NaN   
254  Kansas City Chiefs     9            9           NaN   
255  Kansas City Chiefs    10           10          AWAY   
256  Kansas City Chiefs    11           11          AWAY   
257  Kansas City Chiefs    13           12           NaN   
258  Kansas City Chiefs    14           13          AWAY   
259  Kansas City Chiefs    15           14           NaN   
260  Kansas City Chiefs    16           15          AWAY   
261  Kansas City Chiefs    17           16           NaN   
262  Kansas City Chiefs    19           17           NaN   
263  Kansas City Chiefs    20           18           NaN   

                    Team2  Team1_Score  Team2_Score  Team1_Passing  \
246  Jacksonville Jaguars         40.0         26.0          378.0   
247       Oakland Raiders         28.0         10.0          436.0   
248      Baltimore Ravens         33.0         28.0          363.0   
249         Detroit Lions         34.0         30.0          315.0   
250    Indianapolis Colts         13.0         19.0          288.0   
251        Houston Texans         24.0         31.0          256.0   
252        Denver Broncos         30.0          6.0          191.0   
253     Green Bay Packers         24.0         31.0          249.0   
254     Minnesota Vikings         26.0         23.0          230.0   
255      Tennessee Titans         32.0         35.0          433.0   
256  Los Angeles Chargers         24.0         17.0          180.0   
257       Oakland Raiders         40.0          9.0          163.0   
258  New England Patriots         23.0         16.0          271.0   
259        Denver Broncos         23.0          3.0          327.0   
260         Chicago Bears         26.0          3.0          244.0   
261  Los Angeles Chargers         31.0         21.0          174.0   
262        Houston Texans         51.0         31.0          316.0   
263      Tennessee Titans         35.0         24.0          292.0   

     Team1_Rushing  Team1_Turnovers  Team2_Passing  Team2_Rushing  \
246          113.0                0          347.0           81.0   
247           31.0                1          178.0          129.0   
248          140.0                0          249.0          203.0   
249          123.0                3          261.0          186.0   
250           36.0                1          151.0          180.0   
251           53.0                2          280.0          192.0   
252           80.0                0          134.0           71.0   
253           88.0                1          256.0          118.0   
254          147.0                1          212.0           96.0   
255           97.0                1          146.0          225.0   
256          130.0                1          345.0           93.0   
257           96.0                0          210.0          122.0   
258           75.0                2          184.0           94.0   
259           92.0                1          199.0           52.0   
260          106.0                0          133.0          101.0   
261          162.0                1          258.0          108.0   
262          118.0                1          348.0           94.0   
263          112.0                0          210.0           85.0   

     Team2_Turnovers  
246                2  
247                2  
248                0  
249                2  
250                1  
251                3  
252                1  
253                0  
254                0  
255 

In [31]:
#chiefs = chiefs.groupby('Team1')['Team1_Score'].sum() 
chiefs_score = chiefs['Team1_Score'].mean()
chiefs_pass = chiefs['Team1_Passing'].mean()
chiefs_run = chiefs['Team1_Rushing'].mean()
chiefs_turnover = chiefs['Team1_Turnovers'].mean()
chiefs_turnover

0.8888888888888888

In [32]:
Playoffs = np.array([21, 304, 115, 0.5]).reshape(1, -1)
Whole_season = np.array([21, 284, 99, 0.89 ]).reshape(1, -1)

#Building a random forest 
https://stackabuse.com/random-forest-algorithm-with-python-and-scikit-learn/
https://medium.com/@sametgirgin/random-forest-regression-in-5-steps-with-python-ee4259eca0de

In [7]:
#Splitting into attributes and labels. For game no, pass, rushing, turnovers
X = chiefs.iloc[:, 2].values
Y = chiefs.iloc[:, 7:10].values
# concatenate 2 numpy arrays: column-wise
X = np.column_stack((X,Y))
X

array([[  1., 378., 113.,   0.],
       [  2., 436.,  31.,   1.],
       [  3., 363., 140.,   0.],
       [  4., 315., 123.,   3.],
       [  5., 288.,  36.,   1.],
       [  6., 256.,  53.,   2.],
       [  7., 191.,  80.,   0.],
       [  8., 249.,  88.,   1.],
       [  9., 230., 147.,   1.],
       [ 10., 433.,  97.,   1.],
       [ 11., 180., 130.,   1.],
       [ 12., 163.,  96.,   0.],
       [ 13., 271.,  75.,   2.],
       [ 14., 327.,  92.,   1.],
       [ 15., 244., 106.,   0.],
       [ 16., 174., 162.,   1.],
       [ 17., 316., 118.,   1.],
       [ 18., 292., 112.,   0.]])

In [8]:
type(X)

numpy.ndarray

In [9]:
#Team 1 Score is my Label 
y = chiefs.iloc[:, 5].values
y

array([40., 28., 33., 34., 13., 24., 30., 24., 26., 32., 24., 40., 23.,
       23., 26., 31., 51., 35.])

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)
X_test

array([[  2., 436.,  31.,   1.],
       [  7., 191.,  80.,   0.]])

In [36]:
#Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [37]:
#Using the Super_bowl array as an input
regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X, y)
#y_pred = regressor.predict(Whole_season)
y_pred = regressor.predict(Playoffs)
print(y_pred)

[41.6]


In [38]:
#Using 2 test as input 
regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print(y_pred)

[22.9  26.35]


In [39]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 4.375
Mean Squared Error: 19.66625
Root Mean Squared Error: 4.434664587091114
